In [15]:
import pandas as pd

In [ ]:
df1 = pd.read_csv("output/recordes_natacao_Male.csv")

In [ ]:
df = df1.copy()

In [ ]:
df = df.loc[df["Event"] == "100 FR LCM"]
df.head()

,Rank,Event,Swim Time,Name,Gender,Team,Swimmer Country,Meet,Swim Date
29,1,100 FR LCM,46.40,Zhanle PAN,Male,Peoples Republic of China,Peoples Republic of China,2024 Olympic Games,07/31/2024
30,2,100 FR LCM,46.80,Zhanle PAN,Male,Peoples Republic of China,Peoples Republic of China,2024 World Champs,02/11/2024
31,3,100 FR LCM,46.86,David Popovici,Male,Romania,Romania,LEN European Aquatics Championships,08/13/2022
32,4,100 FR LCM,46.91,Cesar Cielo,Male,Brazil,Brazil,2009 World Champs,07/30/2009
33,5,100 FR LCM,46.94,Alain Bernard,Male,France,France,2009 FRA National Champs,04/23/2009

In [ ]:
df["Year"] = df["Swim Date"].str[-4:]
df["Year"] = pd.to_numeric(df["Year"])
df = df.loc[df["Year"] >1970]
df.drop(columns=["Event", "Gender", "Swim Date", "Swimmer Country"], inplace=True)
df.rename(columns={"Swim Time": "Results", "Meet": "Competition"}, inplace=True)
df.sort_values(by="Year", ascending=False)
df.head()

,Rank,Results,Name,Team,Competition,Year
29,1,46.40,Zhanle PAN,Peoples Republic of China,2024 Olympic Games,2024
30,2,46.80,Zhanle PAN,Peoples Republic of China,2024 World Champs,2024
31,3,46.86,David Popovici,Romania,LEN European Aquatics Championships,2022
32,4,46.91,Cesar Cielo,Brazil,2009 World Champs,2009
33,5,46.94,Alain Bernard,France,2009 FRA National Champs,2009

In [ ]:
df.to_csv("output/recordes_tratados_homens.csv", index=False)

In [13]:
df1 = pd.read_csv("output/recordes_female.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'output/recordes_female.csv'

In [ ]:
df = df1.copy()
df = df.loc[df["Event"] == "100 FR LCM"]
df["Year"] = df["Swim Date"].str[-4:]
df["Year"] = pd.to_numeric(df["Year"])
df = df.loc[df["Year"] >1970]
df.drop(columns=["Event", "Gender", "Swim Date", "Swimmer Country"], inplace=True)
df.rename(columns={"Swim Time": "Results", "Meet": "Competition"}, inplace=True) 
df.sort_values(by="Year", ascending=False)
df.head()

,Rank,Results,Name,Team,Competition,Year
14,1,51.71,Sarah Sjostrom,Sweden,2017 World Champs,2017
15,2,52.06,Cate Campbell,Australia,2016 Swimming Australia Grand Prix,2016
16,3,52.07,Britta Steffen,Germany,2009 World Champs,2009
17,4,52.22,Britta Steffen,Germany,2009 World Champs,2009
18,5,52.56,Britta Steffen,Germany,2008 Olympic Invite,2009

In [ ]:
df.to_csv("output/recordes_tratados_mulheres.csv", index=False)