In [142]:
import pandas as pd

In [ ]:
df1 = pd.read_csv("output/recordes_male.csv")

,Rank,Event,Swim Time,Name,Gender,Team,Swimmer Country,Meet,Swim Date
0,1,50 FR LCM,20.91,Cesar Cielo,Male,Brazil,Brazil,2009 BRA Open,12/18/2009
1,2,50 FR LCM,20.94,Fred Bousquet,Male,France,France,2008 Olympic Invite,04/26/2009
2,3,50 FR LCM,21.28,Eamon Sullivan,Male,Australia,Australia,2008 AUS Olympic Trials,03/28/2008
3,4,50 FR LCM,21.41,Eamon Sullivan,Male,Australia,Australia,NaN,03/27/2008
4,5,50 FR LCM,21.50,Alain Bernard,Male,France,France,2008 European Champs,03/23/2008

In [144]:
df = df1.copy()

In [ ]:
df = df.loc[df["Event"] == "100 FR LCM"]
df.head()

,Rank,Event,Swim Time,Name,Gender,Team,Swimmer Country,Meet,Swim Date
28,1,100 FR LCM,46.40,Zhanle PAN,Male,Peoples Republic of China,Peoples Republic of China,2024 Olympic Games,07/31/2024
29,2,100 FR LCM,46.80,Zhanle PAN,Male,Peoples Republic of China,Peoples Republic of China,2024 World Champs,02/11/2024
30,3,100 FR LCM,46.86,David Popovici,Male,Romania,Romania,LEN European Aquatics Championships,08/13/2022
31,4,100 FR LCM,46.91,Cesar Cielo,Male,Brazil,Brazil,2009 World Champs,07/30/2009
32,5,100 FR LCM,46.94,Alain Bernard,Male,France,France,2009 FRA National Champs,04/23/2009

In [147]:
df["Year"] = df["Swim Date"].str[-4:]
df["Year"] = pd.to_numeric(df["Year"])
df = df.loc[df["Year"] >1970]
df.drop(columns=["Event", "Gender", "Swim Date", "Swimmer Country"], inplace=True)
df.rename(columns={"Swim Time": "Results", "Meet": "Competition"}, inplace=True)
df.sort_values(by="Year", ascending=False)
df.head()

,Rank,Results,Name,Team,Competition,Year
28,1,46.40,Zhanle PAN,Peoples Republic of China,2024 Olympic Games,2024
29,2,46.80,Zhanle PAN,Peoples Republic of China,2024 World Champs,2024
30,3,46.86,David Popovici,Romania,LEN European Aquatics Championships,2022
31,4,46.91,Cesar Cielo,Brazil,2009 World Champs,2009
32,5,46.94,Alain Bernard,France,2009 FRA National Champs,2009

In [148]:
df.to_csv("output/recordes_tratados_homens.csv", index=False)

In [149]:
df1 = pd.read_csv("output/recordes_female.csv")

In [150]:
df = df1.copy()
df = df.loc[df["Event"] == "100 FR LCM"]
df["Year"] = df["Swim Date"].str[-4:]
df["Year"] = pd.to_numeric(df["Year"])
df = df.loc[df["Year"] >1970]
df.drop(columns=["Event", "Gender", "Swim Date", "Swimmer Country"], inplace=True)
df.rename(columns={"Swim Time": "Results", "Meet": "Competition"}, inplace=True) 
df.sort_values(by="Year", ascending=False)
df.head()

,Rank,Results,Name,Team,Competition,Year
14,1,51.71,Sarah Sjostrom,Sweden,2017 World Champs,2017
15,2,52.06,Cate Campbell,Australia,2016 Swimming Australia Grand Prix,2016
16,3,52.07,Britta Steffen,Germany,2009 World Champs,2009
17,4,52.22,Britta Steffen,Germany,2009 World Champs,2009
18,5,52.56,Britta Steffen,Germany,2008 Olympic Invite,2009

In [151]:
df.to_csv("output/recordes_tratados_mulheres.csv", index=False)